### ISSUE TITLE
4.4.0 And missing Symbols

### ISSUE THREAD

**Issue by rblalock** [psharanda/Atributika#27]
Just pod install'd 4.4.0 and am getting the following:

```
Undefined symbols for architecture arm64:
  "protocol witness table for __C.NSAttributedStringKey : Swift.Hashable in Foundation", referenced from:
      function signature specialization <Arg[0] = Owned To Guaranteed, Arg[1] = Dead> of generic specialization <preserving fragile attribute, Atributika.StyleType, [__C.NSAttributedStringKey : Any]> of static (extension in Swift):Swift._NativeDictionaryBuffer< where A: Swift.Hashable>.fromArray([(A, B)]) -> Swift._NativeDictionaryBuffer<A, B> in RegulationDetailController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm not sure this is actually Atributika's problem yet but it's in the error so I thought I"d put it here while I try to track down what is going on.  Anyone else see this?

**Comment by psharanda** [comment]
Does it work fine with Atributika 4.3.x? What Xcode version do you use?

**Comment by rblalock** [comment]
Xcode 9.3 (9E145).  Also, I just noticed this ONLY happens when doing a Build -> Archive .  It works fine in the iOS sim.  And same thing happens in 4.3.x as well.  I think it must have something to do witht he swift / xcode upgrades this past week.  I'm going to start pulling out pods (starting with Atributika) to see if it works then.  Very odd error.

**Comment by rblalock** [comment]
Ok removed attributike from my one controller and from pods and it compiles for archive now.  So now at least I have it narrowed down to that.  I'll start down the rabbit hole this afternoon and see what I can find.  To confirm the error only happens for me when doing a build for Archive in RELEASE mode.

**Comment by rblalock** [comment]
Further troubleshooting this, here's what I found:

```swift
let all = Style.font(FRFont.medium(with: 14))
let link = Style("a").foregroundColor(.blue, .normal).foregroundColor(.brown, .highlighted)

// ...

informationText.attributedText = info.joined(separator: "\n\n").style(tags: [link]).styleAll(all)
```

If I remove this, Archiving will work (the error originally posted will not happen)

**Comment by rblalock** [comment]
It looks like the `style(tags: [Style])` initializer is the culprit.  If I just use `styleLink` it will compile (although it doesn't convert the `a` tag and keeps it as html...which is a separate problem. Looking at the source now.

**Comment by psharanda** [comment]
Looks like I found how to fix. Please let me know if current `master` works for you

**Comment by rblalock** [comment]
That worked!  Out of curiosity, how did you trouble shoot that

**Comment by psharanda** [comment]
Just followed error message that `NSAttributedStringKey` somehow missed `Hashable` protocol support. So just explicitly added it. Likely not the best solution, but at least something

**Comment by psharanda** [comment]
I found that bug is reproducible if reduce lib just to few lines 
``` swift
import Foundation
import UIKit

public struct Style {
    
    public let typedAttributes: [NSAttributedStringKey: Any]
    
    public init(_ attributes: [NSAttributedStringKey: Any] = [:]) {
        typedAttributes = attributes
    }
}
```

**Comment by psharanda** [comment]
That means this is just a bug in `NSAttributedStringKey` somewhere in swift

**Comment by psharanda** [comment]
Alright, reported this bug to https://bugs.swift.org/browse/SR-7326
Thanks for your participation in Atributika development

**Comment by rblalock** [comment]
awesome.  thanks for helping debug this!

**Comment by rushk2112** [comment]
Just a note that in Xcode 9.2 you now get this warning message:

".../Pods/Atributika/Sources/Style.swift:29:34: Conformance of 'NSAttributedStringKey' to protocol 'Hashable' was already stated in the type's module 'Foundation'"

Changing it to the following removes the warning for those using Swift < 4.1
// workaround for https://github.com/psharanda/Atributika/issues/27
#if swift(>=4.1)
	extension NSAttributedStringKey: Hashable { }
#endif

**Comment by psharanda** [comment]
@rushk2112 thanks. your pr is welcome

**Comment by rushk2112** [comment]
Just wanted to mow sure I got my PR committed in properly so it'll get included in future updates. It's my first time doing this kinda of thing.

**Comment by psharanda** [comment]
sorry. but i meant that i am waiting for your PR. it is not yet commited to original repo

**Comment by psharanda** [comment]
thanks, all is set now

**Comment by rushk2112** [comment]
Happy to help... my first contribution to OpenSource! :^)
